package twitter4jads.models.ads;

/**
 * User: poly
 * Date: 30/01/14
 * Time: 11:51 AM
 */
public enum TargetingType {
    LOCATION,
    FOLLOWERS_OF_USER,
    SIMILAR_TO_FOLLOWERS_OF_USER,
    INTEREST,
    PLATFORM,
    PLATFORM_VERSION,
    DEVICE,
    WIFI_ONLY,
    GENDER,
    TV_SHOW,
    TV_CHANNEL,
    TV_GENRE,
    TV_AD_TARGETING,
    TV_MARKET,
    BROAD_KEYWORD,
    UNORDERED_KEYWORD,
    PHRASE_KEYWORD,
    EXACT_KEYWORD,
    NEGATIVE_PHRASE_KEYWORD,
    NEGATIVE_UNORDERED_KEYWORD,
    NEGATIVE_EXACT_KEYWORD,
    TAILORED_AUDIENCE,
    TAILORED_AUDIENCES_EXCLUDED,
    FLEXIBLE_TAILORED_AUDIENCE,
    TAILORED_AUDIENCES_EXPANDED,
    LANGUAGE,
    RTB_APP_CATEGORY,
    NETWORK_OPERATOR,
    NETWORK_ACTIVATION_DURATION_LT,
    NETWORK_ACTIVATION_DURATION,
    NETWORK_ACTIVATION_DURATION_GTE,
    AGE,
    BEHAVIOR,
    NEGATIVE_BEHAVIOR,
    BEHAVIOR_EXPANDED,
    TV_SHOW_AIRING_RESTRICTED,
    APP_STORE_CATEGORY,
    APP_STORE_CATEGORY_LOOKALIKE,
    APP_STORE_CATEGORY_EXPANDED,
    ENGAGEMENT_TYPE,
    CAMPAIGN_ENGAGEMENT,
    EXCLUDE_APP_LIST,
    USER_ENGAGEMENT,
    EVENT,
    CONTENT_PUBLISHER_USER,
    IAB_CATEGORY

}
