package twitter4jads.models;

/**
 * User: Roota
 * Date: 17/02/14.
 */
public enum TwitterSegmentationType {
    PLATFORMS, LOCATIONS, GENDER, INTERESTS, KEYWORDS, CITIES, REGIONS, POSTAL_CODES, DEVICES, PLATFORM_VERSIONS, SIMILAR_TO_FOLLOWERS_OF_USER,
    APP_STORE_CATEGORY, TV_SHOWS, LANGUAGES, EVENTS, CONVERSION_TAGS, AGE
}
